### ISSUE TITLE
Could not find a version that satisfies the requirement dateutil

### ISSUE THREAD

**Issue by ramajuno** [genedan/TmVal#66]
ERROR: Could not find a version that satisfies the requirement dateutil (from tmval) (from versions: none)
ERROR: No matching distribution found for dateutil (from tmval)

seems new version of dateutil not supported

**Comment by genedan** [comment]
Hey, sorry for the late response. The package should have been python-dateutil and not dateutil. I have updated this in the latest version so please try installing via pip again.

**Comment by genedan** [comment]
closed via v0.0.12
